### ISSUE TITLE
[Feat] 쪽지 조회하기

### ISSUE THREAD

**Issue by muunioi** [TransferStay-sbackjung/TransferStay#6]
## ✅ Feat : 쪽지 조회하기
> 새롭게 추가할 기능을 작성해주세요.

## Description
> 기능에 대해 설명해주세요.

사용자 간 주고받은 쪽지를 조회할 수 있습니다

## To-Do
> 작업할 내용을 작성해주세요.
- [ ] 받은 쪽지 조회
- [ ] 보낸 쪽지 조회
- [ ] 받은 쪽지함에서 읽지 않은 쪽지 구별

**Comment by muunioi** [comment]
계획 변경된 기능 - 사용안함
